[package]
name = "bridge"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[profile.dev]
debug = 0

[profile.release]
debug = 0

[dependencies]
bincode = "1.3.3"
rusb = "0.9.4"
serde = { version = "1.0.218", features = ["derive"] }
