[package]
name = "middleware"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[profile.dev]
debug = 0

[profile.release]
debug = 0

[dependencies]
rusb = "0.9.4"
serde = "1.0.218"
